/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_aresrecorderactivity_CameraView */

#ifndef _Included_com_example_aresrecorderactivity_CameraView
#define _Included_com_example_aresrecorderactivity_CameraView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_aresrecorderactivity_CameraView
 * Method:    saveFrameToVideo
 * Signature: (Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_com_example_aresrecorderactivity_CameraView_saveFrameToVideo
  (JNIEnv *, jobject, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
